language: node_js

services:
  - postgresql

node_js:
  - 14

notifications:
  email: false

cache:
  directories:
    - node_modules
    - ~/.npm

install:
  - npm ci
  - npm i -g newman

before_script:
  - psql -c "create database ${POSTGRES_DB};" -U $POSTGRES_USER
  - npm run build --if-present
  - npm run typeorm migration:run
  - npm run fixtures

script:
  - npm run lint --if-present
  - npm run test:cov
  - npm run test:e2e
  - NODE_ENV=production npm start &
  - sleep 10
  - newman run https://www.getpostman.com/collections/6b82b259fc751deda654
